In [30]:
class sgc():
    def __init__(self,name,mark):
        self.name=name
        self.mark=mark
    def subject(self):
        return self.name
    def grade(self):
        if 60<=self.mark<=69:
            return 'A-'
        elif 70<=self.mark<=79:
            return 'A'
        elif 80<=self.mark<=100:
            return 'A+'
        else:
            print('Wrong value')
    def cg(self):
        if 80<=self.mark<=100:
            return 4
        elif 70<=self.mark<=79:
            return 3
        else:
            return 2
                
        

In [31]:
a=sgc('Bangla',80)
print(a.subject())
print(a.grade())
print(a.cg())
a.name,a.mark

Bangla
A+
4


('Bangla', 80)

In [33]:
n=int(input('Enter total subject: '))
t_gpa=0
for i in range(n):
    cg_list=[]
    subject_name=input('Enter subject name: ')
    subject_mark=int(input('Enter subject mark: '))
    globals()[subject_name]=sgc('subject_name',subject_mark)
    t_gpa+= (globals()[subject_name].cg())/n
print(t_gpa)

Enter total subject: 3
Enter subject name: math
Enter subject mark: 85
Enter subject name: phy
Enter subject mark: 65
Enter subject name: che
Enter subject mark: 75
3.0


In [25]:
print(math.grade())
print(phy.grade())
print(che.grade())

A+
A-
A


In [26]:
print(math.cg())
print(phy.cg())
print(che.cg())

CG 4
CG 2
CG 3


# Multiple input
## method (1)


In [34]:
a,b,c=input('Enter numbers').split()

Enter numbers1 2 3


In [35]:
a

'1'

In [36]:
c

'3'

## method (2)

In [37]:
x,y=input('Enter first name: '),input('Enter last name: ')

Enter first name: SRK
Enter last name: Safa


In [38]:
x

'SRK'

In [39]:
y

'Safa'

In [40]:
x,y=[x for x in input('Enter name and age: ').split(",")]

Enter name and age: safa,25


In [41]:
x

'safa'

In [42]:
y

'25'

# Numpy Module

In [43]:
import numpy as np

# creating numpy arrays

In [45]:
a = [1,2,3,4,5]
np.array(a)

array([1, 2, 3, 4, 5])

In [46]:
np.zeros(4)

array([0., 0., 0., 0.])

In [50]:
np.zeros(3)

array([0., 0., 0.])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.zeros(((2,3,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.ones(3)

array([1., 1., 1.])

In [55]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [60]:
np.linspace(0,10,8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

# Random Numbers
## np.random.rand() can be used to create random samples from a uniform distribution over [0, 1).

In [61]:
a=np.random.rand(10)

In [62]:
a


array([0.20840142, 0.05563299, 0.39864885, 0.41007644, 0.98431201,
       0.13469873, 0.30870085, 0.02822752, 0.36697179, 0.14043611])

In [63]:
np.random.randint(0,10,3)

array([5, 8, 2])

In [67]:
np.random.randint(0,10,3)

array([3, 6, 5])

In [69]:
np.random.rand(5,5)

array([[0.2778669 , 0.60804055, 0.99429321, 0.09813308, 0.5449527 ],
       [0.93354701, 0.59210691, 0.3757555 , 0.81870222, 0.24462553],
       [0.36264749, 0.75547424, 0.28227407, 0.01775319, 0.29609942],
       [0.93335587, 0.68750769, 0.06903649, 0.15225666, 0.78300634],
       [0.25169763, 0.38116561, 0.93698028, 0.2042663 , 0.90132678]])

In [70]:
np.random.randn(5)

array([-0.15432804,  0.82825201, -1.92675692, -0.23336307,  0.4039623 ])

In [72]:
np.random.randn(5,5)

array([[ 1.80312024,  1.68520188, -0.37167657,  0.51252724,  0.37186955],
       [-1.87467621,  0.01718536,  1.27744153, -0.11698944,  1.13755076],
       [ 2.72484925, -0.82933687, -0.31522195,  0.01647229, -0.09391398],
       [-0.62077939,  0.14746278, -0.26608171,  0.25421907, -0.63315169],
       [-0.03356151,  0.60261884, -0.79360995, -0.55560025, -2.9875536 ]])

In [73]:
a=np.random.randn(5,5)

In [74]:
type(a)

numpy.ndarray

In [75]:
np.random.randint(1,50)

43

In [83]:
test=np.random.randint(1,50,16)

In [84]:
print(test)

[44 15 26  1 32 11 17 43 12 33 20  5 10 18 26 20]


In [85]:
for i in test:
    print(i)

44
15
26
1
32
11
17
43
12
33
20
5
10
18
26
20


In [86]:
l=list(test)
l

[44, 15, 26, 1, 32, 11, 17, 43, 12, 33, 20, 5, 10, 18, 26, 20]

In [87]:
test.reshape(4,4)

array([[44, 15, 26,  1],
       [32, 11, 17, 43],
       [12, 33, 20,  5],
       [10, 18, 26, 20]])

In [88]:
test.max()

44

In [89]:
test.min()

1

In [91]:
test.argmax() # Return index of max value

0

In [92]:
test.argmin()

3

In [95]:
a=np.random.randint(1,20,size=(3,3))

In [96]:
a

array([[ 8, 15, 18],
       [ 2, 12, 15],
       [ 1,  2,  2]])

In [97]:
b=np.random.randint(1,20,size=(3,3))

In [98]:
b

array([[13,  2, 13],
       [14, 11,  6],
       [19, 16,  3]])

In [100]:
c=a+b

In [101]:
c

array([[21, 17, 31],
       [16, 23, 21],
       [20, 18,  5]])

In [102]:
c-b

array([[ 8, 15, 18],
       [ 2, 12, 15],
       [ 1,  2,  2]])

In [103]:
a*b

array([[104,  30, 234],
       [ 28, 132,  90],
       [ 19,  32,   6]])

In [104]:
a/b

array([[0.61538462, 7.5       , 1.38461538],
       [0.14285714, 1.09090909, 2.5       ],
       [0.05263158, 0.125     , 0.66666667]])

In [107]:
d=np.hstack((a,b))

In [108]:
d

array([[ 8, 15, 18, 13,  2, 13],
       [ 2, 12, 15, 14, 11,  6],
       [ 1,  2,  2, 19, 16,  3]])

In [115]:
d1=np.column_stack((a,b))

In [116]:
d1

array([[ 8, 15, 18, 13,  2, 13],
       [ 2, 12, 15, 14, 11,  6],
       [ 1,  2,  2, 19, 16,  3]])

In [121]:
d2=np.concatenate((a,b),axis=1)

In [122]:
d2

array([[ 8, 15, 18, 13,  2, 13],
       [ 2, 12, 15, 14, 11,  6],
       [ 1,  2,  2, 19, 16,  3]])

In [123]:
e=np.vstack((a,b))

In [124]:
e

array([[ 8, 15, 18],
       [ 2, 12, 15],
       [ 1,  2,  2],
       [13,  2, 13],
       [14, 11,  6],
       [19, 16,  3]])

In [125]:
e1=np.row_stack((a,b))

In [126]:
e1

array([[ 8, 15, 18],
       [ 2, 12, 15],
       [ 1,  2,  2],
       [13,  2, 13],
       [14, 11,  6],
       [19, 16,  3]])

In [127]:
e2=np.concatenate((a,b),axis=0)

In [128]:
e2

array([[ 8, 15, 18],
       [ 2, 12, 15],
       [ 1,  2,  2],
       [13,  2, 13],
       [14, 11,  6],
       [19, 16,  3]])

In [131]:
! pip install random2

^C


In [132]:
!pip install numpy

In [133]:
import random
random.sample(range(100),10)

[29, 81, 98, 47, 32, 86, 21, 27, 20, 82]

In [135]:
np.random.choice(range(20),10,replace='False')

array([19,  6, 19,  0,  4, 16,  7, 19,  5, 11])

In [136]:
a

array([[ 8, 15, 18],
       [ 2, 12, 15],
       [ 1,  2,  2]])

In [137]:
a**2

array([[ 64, 225, 324],
       [  4, 144, 225],
       [  1,   4,   4]])

In [139]:
np.sqrt(a**2)

array([[ 8., 15., 18.],
       [ 2., 12., 15.],
       [ 1.,  2.,  2.]])

In [140]:
l=[1,2,3]
m=[4,5,6]
print(l+m)

[1, 2, 3, 4, 5, 6]


In [141]:
np.max(a)

18

In [142]:
np.argmax(a)

2

In [143]:
np.min(a)

1

In [144]:
np.argmin(a)

6

In [145]:
print(a)

[[ 8 15 18]
 [ 2 12 15]
 [ 1  2  2]]


In [147]:
n=np.log(a)
print(n)

[[2.07944154 2.7080502  2.89037176]
 [0.69314718 2.48490665 2.7080502 ]
 [0.         0.69314718 0.69314718]]


In [148]:
np.log(8)

2.0794415416798357

In [149]:
np.log(100)

4.605170185988092

In [150]:
print(type(a))

<class 'numpy.ndarray'>


In [151]:
o=a.copy()

In [152]:
print(o)

[[ 8 15 18]
 [ 2 12 15]
 [ 1  2  2]]


In [153]:
a>10

array([[False,  True,  True],
       [False,  True,  True],
       [False, False, False]])

In [154]:
a<10

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [160]:
p=[5,6,78,34,56]
q=list(map(lambda x: x>15,p))

In [161]:
print(q)

[False, False, True, True, True]


In [162]:
q1=list(filter(lambda x:x>15,p))

In [163]:
print(q1)

[78, 34, 56]
